// подключаем глобальные стили
import { Header } from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
// подключаем шрифты
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import { Footer } from "@/components/Footer";
import { Providers } from "@/components/Providers";

// настраиваем шрифты
const inter = Inter({ subsets: ["latin"] });

// подключение метаданных на странице
export const metadata: Metadata = {
  title: "My app",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

// компонент, который предназначен для добавления html и body во все файлы. Здесь чилдреном выступает любая страница
const RootLayout = (props: RootLayoutProps) => {
  const { children } = props;

  return (
    <html lang="en">
      {/* подключаем шрифты на страницу */}
      <body className={inter.className}>
        <Providers>
          {/* добавляем хедер и футер, чтоб они появлялись на каждой странице */}
          <Header />
          <main className="container">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
